version: '3'

services:
  web_app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on: 
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_dev
    ports:
      - "3306:3306"
    volumes:
      - ./build/db/log:/var/log/mysql
      - ./build/db/data:/var/lib/mysql
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf